apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: brilliant
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass123
  MYSQL_DATABASE: brilliantdb
  MYSQL_USER: brilliantuser
  MYSQL_PASSWORD: brilliantpass123
