apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: brilliant
data:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "*"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "brilliantdb"
  DB_USER: "brilliantuser"
