apiVersion: v1
kind: Service
metadata:
  name: brilliantapp-svc
  namespace: brilliant
spec:
  selector:
    app: brilliantapp
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
