apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brilliantapp-ingress
  namespace: brilliant
spec:
  ingressClassName: nginx
  rules:
    - host: brilliantapp.zad
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brilliantapp-svc
                port:
                  number: 80
